# Generated by Django 2.2.1 on 2019-12-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_address_is_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycar',
            name='goods_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
