# Generated by Django 2.2.1 on 2019-12-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20191230_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quser',
            old_name='eamil',
            new_name='email',
        ),
    ]
