# Generated by Django 2.2.1 on 2019-12-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('store', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('safe_data', models.DateField()),
                ('picture', models.ImageField(upload_to='store/img')),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
