# Generated by Django 2.2.1 on 2019-12-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
