# Generated by Django 2.2.1 on 2019-12-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_goods_goods_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
